---
apiVersion: v1
kind: Service
metadata:
  name: reactjs-service
spec:
  type: NodePort
  selector:
    app: reactjs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
